services:
    stripperclip.application:
        class: Ink\StripperClip\Console\Application
        arguments:
            - @stripperclip.shim_loader
    stripperclip.shim_loader:
        class: Ink\StripperClip\ShimLoader
