imports:
    - { resource: operations.yml }
    - { resource: symfony_components.yml }
services:
    stripperclip.version:
        class: Ink\StripperClip\Loader\VersionTagLoader
        arguments:
            - "%dir.root%"

    stripperclip.application:
        class: Ink\StripperClip\Console\Application
        arguments:
            - "@service_container"
            - "@stripperclip.version"

    stripperclip.loader.shim:
        class: Ink\StripperClip\Loader\ShimLoader
        arguments:
            - "@finder"
            - "%dir.resources%/shims"

    stripperclip.loader.clip:
        class: Ink\StripperClip\Loader\ClipFileLoader
        arguments:
            - "@finder"
            - "%dir.cwd%"
            - "@console.input"
            - "@console.output"

    stripperclip.dependency_resolver:
        class: Ink\StripperClip\DependencyResolver\Resolver
        arguments:
            - "@stripperclip.application"
            - "@console.input"
            - "@console.output"
