imports:
    - { resource: parameters.yml }
services:
    stripperclip.application:
        class: Ink\StripperClip\Console\Application
        arguments:
            - @service_container
            - %version%
    stripperclip.loader.shim:
        class: Ink\StripperClip\Loader\ShimLoader
    stripperclip.loader.clip:
        class: Ink\StripperClip\Loader\ClipFileLoader
        arguments:
            - @console.input
            - @console.output
    console.output:
        class: Symfony\Component\Console\Output\ConsoleOutput
    console.input:
        class: Symfony\Component\Console\Input\ArgvInput
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem
    stripperclip.operation.file_copier:
        class: Ink\StripperClip\Operation\FileCopier
        arguments:
            - @filesystem
