services:
    console.output:
        class: Symfony\Component\Console\Output\ConsoleOutput
    console.input:
        class: Symfony\Component\Console\Input\ArgvInput
    filesystem:
        scope: prototype
        class: Symfony\Component\Filesystem\Filesystem
    finder:
        scope: prototype
        class: Symfony\Component\Finder\Finder
